version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/{{FOLDER}}    #DONT CHANGE THIS! Directory name will be added in CodeBuild
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
